### PR TITLE
Update location of current meeting notes

### PR DESCRIPTION
**Pull request by kevin-bates**
This pull request updates the Meeting Notes location of the README to point at the 2023 notes page.  I've also updated the 2023 notes to include "backlinks" to years 2020, 2021, and 2022.  (I have not updated the 2021 and 2022 issues to have their respective backlinks, but we can do that independently of a PR - if necessary.)

### CODE REVIEW

**Comment by kevin-bates** [comment]
I'm not sure how to deal with the CI failure, but it looks like previous (merged) PRs had similar issues.

**Comment by blink1073** [comment]
The pre-commit app is enabled for all repos.  You can put in a place holder `.pre-commit-config.yaml` with the content below to fix the error.

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
 ```

**Comment by kevin-bates** [comment]
Thanks Steve.  I'll go ahead and make that part of this PR if that's ok.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
