### PR TITLE
Removing myself from team

### PR DESCRIPTION
**Pull request by blink1073**
I am stepping down from team membership

### CODE REVIEW

**Comment by Zsailer** [comment]
❤️ thank you for everything you've done for this team and the project as a whole, Steve. You are greatly and deeply appreciated! 

Quick follow up—we have an "inactive" team list for folks who previously served on the team but have moved onto other things. I'd love to add you to that list instead of removing you :) How do you feel about that?

**Comment by echarles** [comment]
Thank you so much Steve for all your work to make a vision a real technical implementation which just works. And overall, thank you for all the kind interactions you had with this community.

**Comment by blink1073** [comment]
Thank you both.  I would like to keep the PR as-is.

**Comment by Zsailer** [comment]
You're always welcome here, brother! Wishing you the best going forward! ❤️

**Comment by kevin-bates** [comment]
Hey Steve, I echo Zach and Eric's sentiments.  What you have done for the Jupyter community over the years is truly remarkable.  You have been a tremendous colleague, collaborator, and leader and will be missed - thank you!

**Pull request merged**
